doctrine:
    dbal:
        driver: '%env(resolve:DATABASE_DRIVER)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        dbname: '%env(resolve:DATABASE_NAME)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        server_version: 5.7
        charset: UTF8
        schema_filter: ~^(?!fos_)~

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/packages/doctrine/mapping/domain'
                prefix: 'App\Domain'
                alias: Domain
            Projections:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/packages/doctrine/mapping/projection'
                prefix: 'App\Infrastructure'
                alias: Projection
