nelmio_cors:
    defaults:
        allow_origin:   ["*"]
        allow_headers:  ["content-type", "Authorization", "Access-Control-Allow-Origin"]
        allow_methods:  ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        expose_headers: ["link","total-items","current-page","last-page"]
        max_age:        3600
    paths:
        '^/':
            allow_origin:   [ "*" ]
            allow_headers: [ "X-Custom-Auth", "Authorization" ]
            allow_methods: [ "POST", "PUT", "GET", "DELETE" ]
            max_age: 3600